"""Custom photo brick-mosaic kit — Hungary unit economics and 30/60/90-day model.

All inputs are ESTIMATES unless marked FACT. Run: python3 -I brick_mosaic_model.py
"""
EUR_HUF = 360            # FACT-ish: EUR/HUF ~358 (Jul 2026, valutafx). Rounded.
VAT_STD = 0.27           # FACT: Hungarian standard VAT
# FACT: alanyi adómentesség (small-business VAT exemption) threshold HUF 20M revenue in 2026, 22M in 2027 (NAV).
# Eligibility for a NEW business choosing it at registration: verify with an accountant.

# Offers (gross HUF)
S_PRICE, M_PRICE, WRAP_PRICE = 19_990, 29_990, 1_990
MIX_S, MIX_M, WRAP_ATTACH = 0.55, 0.45, 0.30

# Landed product cost per kit (HUF). Bricks: AliExpress 1x1 round plates listed $1.09 (promo) to $10–25 per 1,000;
# Amazon/Walmart retail $12.99–14.99 per 1,000. Model uses €0.006/plate incl. shipping and import (ESTIMATE).
PLATE_EUR = 0.006
S_PLATES, M_PLATES = 1_130, 2_535      # 32x32 and 48x48 (+10% spare)
S_BASE_EUR, M_BASE_EUR = 2.5, 4.5      # baseplates (retail 48x48 ~$15; bulk lower — ESTIMATE)
BOX_INSTR_EUR = 1.2                    # box, printed Hungarian instruction booklet, bags
S_COGS = (S_PLATES * PLATE_EUR + S_BASE_EUR + BOX_INSTR_EUR) * EUR_HUF
M_COGS = (M_PLATES * PLATE_EUR + M_BASE_EUR + BOX_INSTR_EUR) * EUR_HUF
WRAP_COST = 300
SHIP = 1_300          # parcel locker/courier cost to merchant (ESTIMATE; no 2026 webshop rate found)
PAY_PCT, PAY_FIX = 0.022, 100
REMAKE = 0.03         # remake/missing-pieces allowance (personalised goods: no 14-day withdrawal right)
FIXED_EUR = 100       # Shopify Basic, apps, accountant share, domain (ESTIMATE)


def per_order(vat):
    gross = MIX_S * S_PRICE + MIX_M * M_PRICE + WRAP_ATTACH * WRAP_PRICE
    net = gross / (1 + vat)
    cogs = MIX_S * S_COGS + MIX_M * M_COGS + WRAP_ATTACH * WRAP_COST
    pay = PAY_PCT * gross + PAY_FIX
    remake = REMAKE * net
    contrib = net - cogs - SHIP - pay - remake
    gm = (net - cogs) / net
    return dict(gross=gross, net=net, cogs=cogs, pay=pay, remake=remake, contrib=contrib, gm=gm)


# Scenario months: (ad budget €, CPM €, link CTR, purchase CVR, organic share of paid orders)
# CPM benchmark FACT: Poland $5.50 (4.50–6.80), Czechia $6.20; Hungary not listed (adamigo/adligator) -> €4.5–7 assumed.
SCEN = {
    "Conservative": [(350, 6.0, 0.010, 0.008, 0.0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)],   # kill after M1
    "Realistic":    [(350, 6.0, 0.014, 0.011, 0.10), (700, 7.0, 0.016, 0.015, 0.10), (600, 4.5, 0.014, 0.012, 0.10)],
    "Upside":       [(350, 6.5, 0.022, 0.018, 0.25), (1200, 7.0, 0.025, 0.024, 0.25), (1200, 4.5, 0.022, 0.019, 0.25)],
}
MONTHS = ["M1 Nov (test)", "M2 Dec 1–18 (Christmas)", "M3 Jan–mid-Feb (Valentine's)"]


def run():
    o = []
    w = o.append
    w("# Brick-mosaic kit — Hungary model (generated by brick_mosaic_model.py)\n")
    w(f"All values are ESTIMATES. €1 = {EUR_HUF} HUF. CAC/CPA unverified until the ad test.\n")
    w(f"Kit landed cost: S (32×32) ≈ {S_COGS:,.0f} HUF (€{S_COGS/EUR_HUF:.1f}); M (48×48) ≈ {M_COGS:,.0f} HUF (€{M_COGS/EUR_HUF:.1f}).\n")
    for label, vat in (("VAT-exempt (alanyi adómentes)", 0.0), ("Standard VAT 27%", VAT_STD)):
        u = per_order(vat)
        w(f"\n## Per order — {label}\n")
        w("| Line | HUF | € |\n|---|---:|---:|")
        for k, name in (("gross", "Gross AOV (55% S / 45% M, 30% gift wrap)"), ("net", "Net revenue"), ("cogs", "− Landed product cost")):
            w(f"| {name} | {u[k]:,.0f} | {u[k]/EUR_HUF:.1f} |")
        w(f"| − Shipping | {SHIP:,} | {SHIP/EUR_HUF:.1f} |")
        w(f"| − Payment fees | {u['pay']:,.0f} | {u['pay']/EUR_HUF:.1f} |")
        w(f"| − Remake allowance (3%) | {u['remake']:,.0f} | {u['remake']/EUR_HUF:.1f} |")
        w(f"| **Contribution = break-even CAC** | **{u['contrib']:,.0f}** | **{u['contrib']/EUR_HUF:.1f}** |")
        w(f"| Gross margin (net − product) | {u['gm']:.0%} | |")
        c = u["contrib"] / EUR_HUF
        w("\nProfit per order at CAC €10 / €15 / €20 / €25 / €30 / €35: " + " / ".join(f"€{c - x:+.1f}" for x in (10, 15, 20, 25, 30, 35)))
        w("\nOrders/month needed for profit (paid orders, fixed €100): " + "; ".join(
            f"€{t}: " + ", ".join(("n/a" if c - x <= 0 else f"{(t + FIXED_EUR) / (c - x):.0f}") + f" @CAC €{x}" for x in (15, 20, 25))
            for t in (500, 1000, 1500, 2000)))
        for sc, months in SCEN.items():
            w(f"\n### {sc} — {label}\n")
            w("| Month | Ad € | CPM € | CTR | CVR | Sessions | CPA € | Orders (paid+organic) | Revenue HUF | Gross profit € | Profit after ads & fixed € |")
            w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
            cum = 0.0
            for m, (b, cpm, ctr, cvr, org) in zip(MONTHS, months):
                if b == 0:
                    w(f"| {m} | 0 | – | – | – | – | – | stopped (kill rule) | 0 | 0 | 0 |")
                    continue
                cpc = cpm / 1000 / ctr
                sessions = b / cpc
                paid = sessions * cvr
                orders = paid * (1 + org)
                rev = orders * u["gross"]
                gp = orders * c
                profit = gp - b - FIXED_EUR
                cum += profit
                w(f"| {m} | {b} | {cpm:.1f} | {ctr:.1%} | {cvr:.1%} | {sessions:,.0f} | {b/paid:.1f} | {orders:.0f} | {rev:,.0f} | {gp:,.0f} | {profit:,.0f} |")
            w(f"\n90-day cumulative: **€{cum:,.0f}**")
    w("\n## Sensitivity: CPA at CPM €6 for CTR × CVR\n")
    w("| CTR \\ CVR | 0.8% | 1.0% | 1.2% | 1.5% | 2.0% |\n|---|---:|---:|---:|---:|---:|")
    for ctr in (0.010, 0.012, 0.015, 0.020):
        w(f"| {ctr:.1%} | " + " | ".join(f"€{6/1000/ctr/cvr:.0f}" for cvr in (0.008, 0.010, 0.012, 0.015, 0.020)) + " |")
    return "\n".join(o)


if __name__ == "__main__":
    print(run())
