"""Unit economics + 30/60/90-day scenarios for the three finalists.

Every input below is an ESTIMATE unless a comment says FACT.
Run:  python3 -I unit_economics.py  > 06_unit_economics_output.md
"""

VAT = 0.19            # FACT: German standard VAT rate (AT is 20%, ignored for simplicity)
PAY_PCT, PAY_FIX = 0.025, 0.25   # ESTIMATE blended Shopify Payments / PayPal / Klarna
FIXED_MONTHLY = 450   # ESTIMATE: Shopify Basic ~36, apps ~60, email ~30, legal texts ~25, UGC/creative ~300

MONTHS = ["M1 (Nov, Q4 launch)", "M2 (Dec, gifting peak)", "M3 (Jan, new-year hobby / cheap CPM)"]

PRODUCTS = {
    "Crochet starter kit (DACH)": dict(
        cogs_pct_gross=0.16,  # landed kit cost ~16% of gross price (starter €34.90 -> ~€4.80-5.60)
        packaging=0.40, fulfil=2.00, ship=4.00,
        ship_threshold=39.0, ship_fee=3.95,
        returns_pct_net=0.03,
        scenarios={
            # per month: (AOV gross €, CPM €, link CTR, CVR, ad budget €, share of orders below free-ship threshold)
            "Conservative": [(40, 12.0, 0.012, 0.020, 1500, 0.55), (42, 13.0, 0.013, 0.024, 1500, 0.50), (44, 8.5, 0.012, 0.020, 1500, 0.45)],
            "Realistic":    [(44, 12.0, 0.014, 0.026, 1500, 0.45), (48, 13.0, 0.016, 0.030, 2500, 0.35), (52, 8.0, 0.015, 0.024, 3500, 0.30)],
            "Upside":       [(48, 11.0, 0.018, 0.030, 1500, 0.35), (54, 12.0, 0.020, 0.035, 3500, 0.25), (58, 7.5, 0.018, 0.030, 6000, 0.20)],
        },
        repeat_rate={"Conservative": 0.05, "Realistic": 0.08, "Upside": 0.12},  # monthly reorders as share of prior customers
    ),
    "Acupressure wind-down set (DE/AT/NL)": dict(
        cogs_pct_gross=0.21,  # landed ~€13.50 on €64 AOV (FACT input: Alibaba-type set $8.30–9 @MOQ100; premium materials + freight on top)
        packaging=0.80, fulfil=2.30, ship=5.00,
        ship_threshold=0.0, ship_fee=0.0,   # always free shipping at this price point
        returns_pct_net=0.06,               # body-contact product: returns often not resellable
        scenarios={
            "Conservative": [(62, 12.0, 0.010, 0.014, 1500, 0.0), (64, 13.0, 0.011, 0.016, 1500, 0.0), (64, 8.5, 0.010, 0.014, 1500, 0.0)],
            "Realistic":    [(64, 12.0, 0.012, 0.018, 1500, 0.0), (68, 13.0, 0.013, 0.021, 2500, 0.0), (70, 8.0, 0.012, 0.018, 3500, 0.0)],
            "Upside":       [(68, 11.0, 0.015, 0.022, 1500, 0.0), (72, 12.0, 0.016, 0.025, 3500, 0.0), (74, 7.5, 0.015, 0.022, 6000, 0.0)],
        },
        repeat_rate={"Conservative": 0.01, "Realistic": 0.02, "Upside": 0.03},
    ),
    "54 mm espresso workflow kit (DE/AT/NL)": dict(
        cogs_pct_gross=0.22,
        packaging=0.50, fulfil=2.00, ship=4.00,
        ship_threshold=39.0, ship_fee=3.95,
        returns_pct_net=0.05,               # fit/compatibility returns
        scenarios={
            "Conservative": [(45, 12.0, 0.008, 0.020, 1500, 0.0), (46, 13.0, 0.009, 0.022, 1500, 0.0), (47, 8.5, 0.008, 0.020, 1500, 0.0)],
            "Realistic":    [(47, 12.0, 0.010, 0.025, 1500, 0.0), (50, 13.0, 0.011, 0.027, 2500, 0.0), (52, 8.0, 0.010, 0.025, 3500, 0.0)],
            "Upside":       [(50, 11.0, 0.013, 0.030, 1500, 0.0), (54, 12.0, 0.014, 0.032, 3500, 0.0), (56, 7.5, 0.013, 0.030, 6000, 0.0)],
        },
        repeat_rate={"Conservative": 0.01, "Realistic": 0.02, "Upside": 0.03},
    ),
}


def per_order(p, aov, share_below):
    net = aov / (1 + VAT)
    ship_rev = share_below * p["ship_fee"] / (1 + VAT)
    cogs = p["cogs_pct_gross"] * aov
    pay = PAY_PCT * (aov + share_below * p["ship_fee"]) + PAY_FIX
    returns = p["returns_pct_net"] * net
    var = cogs + p["packaging"] + p["fulfil"] + p["ship"] + pay + returns
    contrib = net + ship_rev - var
    gm = (net - cogs - p["packaging"]) / net
    return dict(net=net, ship_rev=ship_rev, cogs=cogs, pay=pay, returns=returns, var=var, contrib=contrib, gm=gm)


def cpa(cpm, ctr, cvr):
    return cpm / 1000 / ctr / cvr


def run():
    out = []
    w = out.append
    w("# Unit economics and 30/60/90-day scenarios (generated by unit_economics.py)\n")
    w("All figures are **ESTIMATES** built from the inputs in the script. CAC/CPA is an assumption and must be validated with real ad tests.\n")
    w(f"Common assumptions: VAT {VAT:.0%} (DE); payment fees {PAY_PCT:.1%} + €{PAY_FIX:.2f}; fixed costs €{FIXED_MONTHLY}/month.\n")
    for name, p in PRODUCTS.items():
        w(f"\n## {name}\n")
        # unit economics at realistic M2 AOV
        aov, *_rest, share = p["scenarios"]["Realistic"][1]
        u = per_order(p, aov, share)
        w(f"### Per-order economics at realistic AOV €{aov:.2f} (gross)\n")
        w("| Line | € per order |\n|---|---:|")
        w(f"| Net revenue (ex VAT) | {u['net']:.2f} |")
        w(f"| + Shipping fees collected (net) | {u['ship_rev']:.2f} |")
        w(f"| − Landed product cost | {u['cogs']:.2f} |")
        w(f"| − Packaging | {p['packaging']:.2f} |")
        w(f"| − 3PL pick & pack | {p['fulfil']:.2f} |")
        w(f"| − Postage | {p['ship']:.2f} |")
        w(f"| − Payment fees | {u['pay']:.2f} |")
        w(f"| − Returns/refund allowance | {u['returns']:.2f} |")
        w(f"| **Contribution before ads = break-even CAC** | **{u['contrib']:.2f}** |")
        w(f"| Gross margin (net price − product − packaging) | {u['gm']:.0%} |")
        w(f"| Target CAC (keep 35% of contribution as profit) | {u['contrib']*0.65:.2f} |")
        w(f"| Contribution after target CAC | {u['contrib']*0.35:.2f} |\n")

        for sc, months in p["scenarios"].items():
            w(f"### {sc} scenario\n")
            w("| Month | AOV € | CPM € | CTR | CVR | CPA € | Ad spend € | New orders | Repeat orders | Revenue € (gross) | Contribution before ads € | Profit after ads & fixed € |")
            w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
            customers = 0
            cum = 0.0
            for m, (aov, cpm, ctr, cvr, budget, share) in zip(MONTHS, months):
                u = per_order(p, aov, share)
                c = cpa(cpm, ctr, cvr)
                new = budget / c
                rep = customers * p["repeat_rate"][sc]
                orders = new + rep
                rev = orders * (aov + share * p["ship_fee"])
                contrib = orders * u["contrib"]
                profit = contrib - budget - FIXED_MONTHLY
                cum += profit
                customers += new
                w(f"| {m} | {aov:.0f} | {cpm:.1f} | {ctr:.1%} | {cvr:.1%} | {c:.1f} | {budget:,.0f} | {new:.0f} | {rep:.0f} | {rev:,.0f} | {contrib:,.0f} | {profit:,.0f} |")
            w(f"\nCumulative 90-day profit/loss: **€{cum:,.0f}**\n")

        # profit targets at steady state using realistic M3 inputs
        aov, cpm, ctr, cvr, budget, share = p["scenarios"]["Realistic"][2]
        u = per_order(p, aov, share)
        w("### Orders per month needed for profit targets (paid new orders only, no repeat)\n")
        w("| Target profit / month | at CPA €18 | at CPA €22 | at CPA €26 | at CPA €30 |\n|---|---:|---:|---:|---:|")
        for target in (500, 1000, 1500, 2000):
            cells = []
            for test_cpa in (18, 22, 26, 30):
                margin = u["contrib"] - test_cpa
                n = (target + FIXED_MONTHLY) / margin if margin > 0 else float("inf")
                cells.append("not reachable" if margin <= 0 else ("not realistic (>2,000)" if n > 2000 else f"{n:,.0f}"))
            w(f"| €{target:,} | " + " | ".join(cells) + " |")
        w(f"\n(Contribution per order used: €{u['contrib']:.2f} at AOV €{aov}.)\n")
    return "\n".join(out)


if __name__ == "__main__":
    print(run())
