"""Scenario model — Hungarian Shopify Opportunity Hunter 2026.

Every input is an ESTIMATE unless marked. No real sales, CAC or supplier
quotes exist; this model only shows what has to be true for each finalist.
"""
EUR_HUF = 360            # FACT-ish: EUR/HUF ~358-360 (2026)
PAY_PCT, PAY_FIX = 0.022, 100   # ESTIMATE: Shopify Payments / Barion-class fees
SHIP = 1_300             # ESTIMATE: locker shipping cost absorbed by store (Ft)
RETURNS = 0.03           # ESTIMATE: returns/remakes as share of net revenue
LABOR_RATE = 3_000       # ESTIMATE: owner time valued at 3,000 Ft/h
FIXED_EUR = 100          # ESTIMATE: Shopify + apps + EPR admin per month

FINALISTS = {
    # name: (price Ft, COGS Ft landed incl. box/print, labour minutes per order)
    "A. Angler gift box (non-angler buyer, Christmas)": (24_990, 8_500, 15),
    "B. Firewood heating-efficiency bundle":            (24_990, 9_400, 8),
}

def contrib(price, cogs, minutes, vat):
    net = price / (1 + vat)
    pay = PAY_PCT * price + PAY_FIX
    labour = minutes / 60 * LABOR_RATE
    return net - cogs - SHIP - pay - RETURNS * net - labour, net

# CAC scenarios (Ft per order) drawn from Hungarian agency benchmark range
# CPA 3,500-25,000 Ft (Tier 3 sources). New store, cold traffic, Q4 CPM spike.
CAC = {"upside": 6_000, "realistic": 10_000, "conservative": 16_000}

# 90-day path: monthly ad spend (EUR) and orders under each scenario.
# Month 1 = validation (Oct/Nov), Month 2 = December peak, Month 3 = January.
PLAN_EUR = [300, 700, 300]
SEASON = {  # multiplier on orders-per-euro vs. month-1 efficiency (ESTIMATE)
    "A. Angler gift box (non-angler buyer, Christmas)": [1.0, 1.4, 0.4],
    "B. Firewood heating-efficiency bundle":            [1.0, 1.1, 0.8],
}
ORGANIC = 0.10           # ESTIMATE: extra orders from organic/word of mouth

def fmt(x):
    return f"{x:,.0f}".replace(",", " ")

out = ["# Model output — Hungarian Shopify Opportunity Hunter 2026", "",
       "All figures ESTIMATE. Generated by `python3 -I model.py`.", ""]
for name, (price, cogs, mins) in FINALISTS.items():
    out += [f"## {name}", "",
            f"Price {fmt(price)} Ft · landed COGS {fmt(cogs)} Ft · "
            f"gross margin on gross price {100*(1-cogs/price):.0f}% · "
            f"labour {mins} min/order", ""]
    out += ["| VAT regime | Net revenue | Contribution / order | = break-even CAC (EUR) |",
            "|---|---|---|---|"]
    for label, vat in (("alanyi adómentes (0%)", 0.0), ("27% VAT", 0.27)):
        c, net = contrib(price, cogs, mins, vat)
        out.append(f"| {label} | {fmt(net)} Ft | {fmt(c)} Ft | {c/EUR_HUF:.1f} |")
    out.append("")
    out += ["### 30/60/90 (VAT-exempt)", "",
            "| Scenario | CAC Ft | M1 orders | M1 profit € | M2 orders | M2 profit € | M3 orders | M3 profit € | 90-day cum. € |",
            "|---|---|---|---|---|---|---|---|---|"]
    c0, _ = contrib(price, cogs, mins, 0.0)
    for sc, cac in CAC.items():
        cum, cells = 0.0, []
        for m, (ad, mult) in enumerate(zip(PLAN_EUR, SEASON[name])):
            orders = ad * EUR_HUF / cac * mult * (1 + ORGANIC)
            profit = (orders * c0 - ad * EUR_HUF) / EUR_HUF - FIXED_EUR
            cum += profit
            cells += [f"{orders:.0f}", f"{profit:+.0f}"]
        out.append(f"| {sc} | {fmt(cac)} | " + " | ".join(cells) + f" | {cum:+.0f} |")
    out.append("")
    # what's needed for EUR 500/month
    need_orders = lambda cac: (500 + FIXED_EUR) * EUR_HUF / (c0 - cac) if c0 > cac else float("inf")
    out += ["### Orders/month needed for €500 net (VAT-exempt)", "",
            "| CAC Ft | Orders needed | Ad spend € |", "|---|---|---|"]
    for cac in (6_000, 8_000, 10_000, 12_000):
        n = need_orders(cac)
        out.append(f"| {fmt(cac)} | {'not reachable' if n == float('inf') else f'{n:.0f}'} | "
                   f"{'—' if n == float('inf') else f'{n*cac/EUR_HUF:.0f}'} |")
    out.append("")

print("\n".join(out))
